package com.example.compose
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF2b50d7)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFdce1ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001159)
val md_theme_light_secondary = Color(0xFF006e23)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF77fd89)
val md_theme_light_onSecondaryContainer = Color(0xFF002106)
val md_theme_light_tertiary = Color(0xFF883f9d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFfdd6ff)
val md_theme_light_onTertiaryContainer = Color(0xFF330044)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF211a1a)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF211a1a)
val md_theme_light_surfaceVariant = Color(0xFFe2e1ec)
val md_theme_light_onSurfaceVariant = Color(0xFF45464f)
val md_theme_light_outline = Color(0xFF76767f)
val md_theme_light_inverseOnSurface = Color(0xFFfbeeed)
val md_theme_light_inverseSurface = Color(0xFF362f2f)

val md_theme_dark_primary = Color(0xFFb7c4ff)
val md_theme_dark_onPrimary = Color(0xFF00228c)
val md_theme_dark_primaryContainer = Color(0xFF0034c0)
val md_theme_dark_onPrimaryContainer = Color(0xFFdce1ff)
val md_theme_dark_secondary = Color(0xFF5ae070)
val md_theme_dark_onSecondary = Color(0xFF00390e)
val md_theme_dark_secondaryContainer = Color(0xFF005318)
val md_theme_dark_onSecondaryContainer = Color(0xFF77fd89)
val md_theme_dark_tertiary = Color(0xFFf3aeff)
val md_theme_dark_onTertiary = Color(0xFF54026b)
val md_theme_dark_tertiaryContainer = Color(0xFF6e2584)
val md_theme_dark_onTertiaryContainer = Color(0xFFfdd6ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF211a1a)
val md_theme_dark_onBackground = Color(0xFFede0df)
val md_theme_dark_surface = Color(0xFF211a1a)
val md_theme_dark_onSurface = Color(0xFFede0df)
val md_theme_dark_surfaceVariant = Color(0xFF45464f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc6c5cf)
val md_theme_dark_outline = Color(0xFF90909a)
val md_theme_dark_inverseOnSurface = Color(0xFF211a1a)
val md_theme_dark_inverseSurface = Color(0xFFede0df)

val seed = Color(0xFF4d6ef5)
val error = Color(0xFFba1b1b)